# Generated by Django 3.2.4 on 2021-06-30 19:50

from django.db import migrations

def create_data(apps, schema_editor):
    
    Soutenance = apps.get_model('soutenance', 'Soutenance')
    Dossier = apps.get_model('soutenance', 'Dossier')
    Laureat = apps.get_model('soutenance', 'Laureat')
    
    Soutenance(s_id=1, laureat_id=Laureat(l_id=1, nom="Quraishi", prenom="Salah", email="Quraishi@gmail.com"), dossier_id=Dossier(d_id=1, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), theme="ML", type="D", etat="N", sujet="sujet1").save()
    Soutenance(s_id=2, laureat_id=Laureat(l_id=2, nom="Cham", prenom="Baha al Din", email="Cham@gmail.com"), dossier_id=Dossier(d_id=2, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), theme="SQ", type="H", etat="N", sujet="sujet2").save()
    Soutenance(s_id=3, laureat_id=Laureat(l_id=3, nom="Rafa", prenom="Khadijah", email="Rafa@gmail.com"), dossier_id=Dossier(d_id=3, etat="R", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), theme="SQ", type="D", etat="R", sujet="sujet3").save()
    Soutenance(s_id=4, laureat_id=Laureat(l_id=4, nom="Muhab", prenom="Akram", email="Muhab@gmail.com"), dossier_id=Dossier(d_id=4, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), theme="ST", type="D", etat="A", sujet="sujet4").save()
    Soutenance(s_id=5, laureat_id=Laureat(l_id=5, nom="Busr", prenom="Zakiyyah", email="Busr@gmail.com"), dossier_id=Dossier(d_id=5, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), theme="SQ", type="D", etat="A", sujet="sujet5").save()
    Soutenance(s_id=6, laureat_id= Laureat(l_id=6, nom="Madani ", prenom="Rufaydah", email="Madani @gmail.com"), dossier_id=Dossier(d_id=6, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), theme="ML", type="H", etat="A", sujet="sujet6").save()
    Soutenance(s_id=7, laureat_id=Laureat(l_id=7, nom="Mustafa", prenom="Karimah ", email="Mustafa@gmail.com"), dossier_id=Dossier(d_id=7, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), theme="GL", type="H", etat="A", sujet="sujet7").save()
    Soutenance(s_id=8, laureat_id=Laureat(l_id=8, nom="Mufeed", prenom="Jalal", email="Mufeed@gmail.com"), dossier_id=Dossier(d_id=8, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), theme="ST", type="D", etat="A", sujet="sujet8").save()

    
    Dossier(d_id=1, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo").save()
    Dossier(d_id=2, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo").save()
    Dossier(d_id=3, etat="R", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo").save()
    Dossier(d_id=4, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo").save()
    Dossier(d_id=5, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo").save()
    Dossier(d_id=6, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo").save()
    Dossier(d_id=7, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo").save()
    Dossier(d_id=8, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo").save()
    
    
    Laureat(l_id=1, nom="Quraishi", prenom="Salah", email="Quraishi@gmail.com").save()
    Laureat(l_id=2, nom="Cham", prenom="Baha al Din", email="Cham@gmail.com").save()
    Laureat(l_id=3, nom="Rafa", prenom="Khadijah", email="Rafa@gmail.com").save()
    Laureat(l_id=4, nom="Muhab", prenom="Akram", email="Muhab@gmail.com").save()
    Laureat(l_id=5, nom="Busr", prenom="Zakiyyah", email="Busr@gmail.com").save()
    Laureat(l_id=6, nom="Madani ", prenom="Rufaydah", email="Madani @gmail.com").save()
    Laureat(l_id=7, nom="Mustafa", prenom="Karimah ", email="Mustafa@gmail.com").save()
    Laureat(l_id=8, nom="Mufeed", prenom="Jalal", email="Mufeed@gmail.com").save()




    #gestion des jurys
    Jury = apps.get_model('soutenance', 'Jury')
    JuryStn = apps.get_model('soutenance', 'JuryStn')


    Jury(j_id=1,nom="Bahar",prenom="Kahil",domaine_xp="Securité infomatique",type='E',tel_num='07268787418',note=1,email="Bahar@esi.dz").save()
    Jury(j_id=2,nom="Suhail",prenom="Ahmad",domaine_xp="Système d'exploitation",type='E',tel_num='0586897412',note=4,email="Suhail@esi.dz").save()
    Jury(j_id=3,nom="Khouri",prenom="Sarah",domaine_xp="Systèmes d’Information",type='P',tel_num='0526527470',note=6.5,email="Khouri@esi.dz").save()
    Jury(j_id=4,nom="Hakimi",prenom="Yusuf",domaine_xp="Planification et Urbanisation SI,",type='P',tel_num='0696897417',note=2.5,email="Hakimi4@esi.dz").save()
    Jury(j_id=5,nom="Abdullah",prenom="Sadad",domaine_xp="Optimisation Combinatoire",type='P',tel_num='058997432',note=2,email="Abdullah@esi.dz").save()
    Jury(j_id=6,nom="Maloof",prenom="Bahira",domaine_xp="Systèmes embarqués",type='P',tel_num='07268787418',note=1.5,email="Maloof4@esi.dz").save()
    Jury(j_id=7,nom="Rahal",prenom="Malik",domaine_xp="Cryptographie",type='P',tel_num='0526897412',note=1,email="Rahal@esi.dz").save()
    Jury(j_id=8,nom="Malouf",prenom="Hind",domaine_xp="Génie Logiciel",type='P',tel_num='0526527470',note=3,email="Malouf@esi.dz").save()







    JuryStn(js_id=1,role='JU',etat='P',jury_id=Jury(j_id=1,nom="Bahar",prenom="Kahil",domaine_xp="Securité infomatique",type='E',tel_num='07268787418',note=1,email="Bahar@esi.dz"),soutenance_id=Soutenance(s_id=2, laureat_id=Laureat(l_id=2, nom="Cham", prenom="Baha al Din", email="Cham@gmail.com"),
    dossier_id=  Dossier(d_id=2, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo")
    , theme="SQ", type="H", etat="N", sujet="sujet2")).save()

    JuryStn(js_id=2,role='RP',etat='P',jury_id=   Jury(j_id=2,nom="Suhail",prenom="Ahmad",domaine_xp="Système d'exploitation",type='E',tel_num='0586897412',note=4,email="Suhail@esi.dz"),
    soutenance_id=Soutenance(s_id=2, laureat_id=Laureat(l_id=2, nom="Cham", prenom="Baha al Din", email="Cham@gmail.com"),
    dossier_id=  Dossier(d_id=2, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo")
  , theme="SQ", type="H", etat="N", sujet="sujet2")).save()

    JuryStn(js_id=3,role='DJ',etat='P',jury_id=  Jury(j_id=6,nom="Maloof",prenom="Bahira",domaine_xp="Systèmes embarqués",type='P',tel_num='07268787418',note=1.5,email="Maloof4@esi.dz")  ,
    soutenance_id=Soutenance(s_id=2, laureat_id=Laureat(l_id=2, nom="Cham", prenom="Baha al Din", email="Cham@gmail.com"),
    dossier_id=  Dossier(d_id=2, etat="V", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo")
  , theme="SQ", type="H", etat="N", sujet="sujet2")).save()




    JuryStn(js_id=4,role='DJ',etat='P',jury_id=  Jury(j_id=7,nom="Rahal",prenom="Malik",domaine_xp="Cryptographie",type='P',tel_num='0526897412',note=1,email="Rahal@esi.dz"),
    soutenance_id= Soutenance(s_id=4, laureat_id=Laureat(l_id=4, nom="Muhab", prenom="Akram", email="Muhab@gmail.com"), 
    dossier_id=Dossier(d_id=4, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), 
    theme="ST", type="D", etat="A", sujet="sujet4")).save()

    JuryStn(js_id=5,role='RP',etat='P',jury_id=  Jury(j_id=3,nom="Khouri",prenom="Sarah",domaine_xp="Systèmes d’Information",type='P',tel_num='0526527470',note=6.5,email="Khouri@esi.dz"),
    soutenance_id= Soutenance(s_id=4, laureat_id=Laureat(l_id=4, nom="Muhab", prenom="Akram", email="Muhab@gmail.com"), 
    dossier_id=Dossier(d_id=4, etat="A", lien="https://drive.google.com/drive/folders/1DWJMlNb0UTU0R6vPNbLRJq7rdzQcTDFo"), 
    theme="ST", type="D", etat="A", sujet="sujet4")).save()















class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(create_data),
    ]
